version: '3.9'

services:
  db:
    container_name: db-fsp
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    container_name: backend-fsp
    build: 
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"


volumes:
  db-data: