"""empty message

Revision ID: 360885ad64b5
Revises: 8cdf3cc9b969
Create Date: 2023-09-04 01:23:39.462716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360885ad64b5'
down_revision = '8cdf3cc9b969'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'FSP_city', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FSP_city', type_='unique')
    # ### end Alembic commands ###
