"""empty message

Revision ID: b505035bfb3a
Revises: 360885ad64b5
Create Date: 2023-09-04 10:37:18.147800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b505035bfb3a'
down_revision = '360885ad64b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
